language: c
sudo: false
addons:
  apt:
    packages:
      - gperf
script:
  - scripts/download-d8.sh
  - make everything
  - test/run-tests.py -v
  - test/run-tests.py -e out/sexpr-wasm-asan -v
  - test/run-tests.py -e out/sexpr-wasm-msan -v
  - test/run-tests.py -e out/sexpr-wasm-lsan -v
compiler:
  - clang
  - gcc
