language: c
sudo: required
dist: trusty
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq flex bison
script:
  - scripts/download-d8.sh
  - rm src/wasm-flex-lexer.c
  - rm src/wasm-bison-parser.{c,h}
  - make everything
  - test/run-tests.py
  - test/run-tests.py -e out/sexpr-wasm-asan --timeout=10
  - test/run-tests.py -e out/sexpr-wasm-msan --timeout=10
  - test/run-tests.py -e out/sexpr-wasm-lsan --timeout=10
  - test/run-tests.py -a=--use-libc-allocator
  - test/run-tests.py -e out/sexpr-wasm-asan -a=--use-libc-allocator --timeout=10
  - test/run-tests.py -e out/sexpr-wasm-msan -a=--use-libc-allocator --timeout=10
  - test/run-tests.py -e out/sexpr-wasm-lsan -a=--use-libc-allocator --timeout=10
compiler:
  - clang
  - gcc
