language: c
sudo: false
addons:
  apt:
    packages:
      - gperf
script:
  - scripts/download-d8.sh
  - make everything
  - test/run-tests.py
  - test/run-tests.py -e out/sexpr-wasm-asan --timeout=10
  - test/run-tests.py -e out/sexpr-wasm-msan --timeout=10
  - test/run-tests.py -e out/sexpr-wasm-lsan --timeout=10
compiler:
  - clang
  - gcc
